/**
 * Generates src/data/stocks.ts — a real snapshot of the S&P 100.
 *
 * Usage: bun run gen:stocks
 *
 * Per company: real price, real 24h change (vs previous session close), real
 * session volume and the official name come from Yahoo's public chart API
 * (no key). Market cap = real price × shares outstanding (see stock-universe.ts
 * — approximate to a few %). Logos are the company domain's favicon PNG via
 * Google's favicon service. Re-run any time to refresh the snapshot.
 */
import { writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { hashStr } from "../src/lib/random";
import { universe, type UniverseEntry } from "./stock-universe";

const CONCURRENCY = 8;

type ChartResponse = {
  chart?: {
    result?: Array<{
      meta?: {
        shortName?: string;
        longName?: string;
        regularMarketPrice?: number;
        regularMarketVolume?: number;
        chartPreviousClose?: number;
      };
      indicators?: { quote?: Array<{ close?: (number | null)[] }> };
    }>;
  };
};

type Quote = { name: string; priceUsd: number; change24hPct: number; vol24hUsd: number };

function yahooSymbol(ticker: string): string {
  return ticker.replace(/\./g, "-"); // Yahoo lists class-B shares as BRK-B
}

async function fetchChart(symbol: string): Promise<ChartResponse> {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5d&interval=1d`;
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (compatible; flaunch-demo/1.0)" },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return (await res.json()) as ChartResponse;
}

async function quoteFor(entry: UniverseEntry): Promise<Quote | null> {
  for (const symbol of [entry.ticker, ...(entry.altTickers ?? [])]) {
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const result = (await fetchChart(yahooSymbol(symbol))).chart?.result?.[0];
        const meta = result?.meta;
        const price = meta?.regularMarketPrice;
        if (!result || price === undefined || price === null) break; // unknown symbol → try alias

        const closes = (result.indicators?.quote?.[0]?.close ?? []).filter(
          (c): c is number => typeof c === "number",
        );
        // 24h change: today's price vs the previous session's close.
        const prevClose = closes.length >= 2 ? closes[closes.length - 2] : meta?.chartPreviousClose;
        const change24hPct = prevClose ? (price / prevClose - 1) * 100 : 0;
        return {
          name: meta?.shortName ?? meta?.longName ?? entry.ticker,
          priceUsd: price,
          change24hPct: Math.round(change24hPct * 100) / 100,
          vol24hUsd: Math.round((meta?.regularMarketVolume ?? 0) * price),
        };
      } catch (err) {
        if (attempt === 1) {
          console.error(`  ${symbol}: ${err instanceof Error ? err.message : String(err)}`);
        }
        await new Promise((resolve) => setTimeout(resolve, 500));
      }
    }
  }
  return null;
}

async function mapPool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const index = next++;
      results[index] = await fn(items[index]!);
    }
  }
  await Promise.all(Array.from({ length: limit }, worker));
  return results;
}

const fetched = await mapPool(universe, CONCURRENCY, async (entry) => ({
  entry,
  quote: await quoteFor(entry),
}));

const missing = fetched.filter((f) => f.quote === null).map((f) => f.entry.ticker);
if (missing.length > 0) console.error(`No quote for: ${missing.join(", ")} — skipped.`);

const rows = fetched
  .filter((f): f is { entry: UniverseEntry; quote: Quote } => f.quote !== null)
  .map(({ entry, quote }) => ({
    ticker: entry.ticker.toUpperCase(),
    name: quote.name,
    priceUsd: quote.priceUsd,
    mcapUsd: Math.round(quote.priceUsd * entry.sharesB * 1e9),
    change24hPct: quote.change24hPct,
    vol24hUsd: quote.vol24hUsd,
    image: `https://www.google.com/s2/favicons?domain=${entry.domain}&sz=128`,
    tvSymbol: `${entry.exchange}:${entry.ticker}`,
    hue: hashStr(entry.ticker) % 360,
    hue2: (hashStr(entry.ticker + entry.domain) + 40) % 360,
  }));

if (rows.length === 0) {
  console.error("No stock quotes fetched — nothing written.");
  process.exit(1);
}

const out: string[] = [];
out.push(
  "// AUTO-GENERATED by `bun run gen:stocks` (real Yahoo Finance snapshot) — do not edit by hand.",
);
out.push("// Market cap = real price × approximate shares outstanding. Re-run to refresh prices.");
out.push("");
out.push("export type StockSeed = {");
out.push("  ticker: string;");
out.push("  name: string;");
out.push("  priceUsd: number;");
out.push("  mcapUsd: number;");
out.push("  change24hPct: number;");
out.push("  vol24hUsd: number;");
out.push("  image: string | null;");
out.push("  tvSymbol: string;");
out.push("  hue: number;");
out.push("  hue2: number;");
out.push("};");
out.push("");
out.push("export const stockSeeds: StockSeed[] = [");
for (const r of rows) {
  out.push(
    `  { ticker: ${JSON.stringify(r.ticker)}, name: ${JSON.stringify(r.name)}, ` +
      `priceUsd: ${r.priceUsd}, mcapUsd: ${r.mcapUsd}, change24hPct: ${r.change24hPct}, ` +
      `vol24hUsd: ${r.vol24hUsd}, image: ${JSON.stringify(r.image)}, ` +
      `tvSymbol: ${JSON.stringify(r.tvSymbol)}, hue: ${r.hue}, hue2: ${r.hue2} },`,
  );
}
out.push("];");
out.push("");

const outPath = fileURLToPath(new URL("../src/data/stocks.ts", import.meta.url));
writeFileSync(outPath, out.join("\n"));
console.log(`Fetched ${rows.length}/${universe.length} stocks → src/data/stocks.ts`);
