/**
 * Generates src/data/stocks.ts — the top US-listed stocks by real market cap.
 *
 * Usage: bun run gen:stocks
 *
 * Source: Nasdaq's public screener download across the NASDAQ, NYSE and AMEX
 * exchanges (no key): real market cap, last price, day change and the official
 * name. TradingView symbols are resolved via symbol search so every stock gets
 * a real candlestick chart. Logos use the curated domains in
 * scripts/stock-universe.ts (S&P 100); stocks without a curated domain fall
 * back to the gradient art rather than risking a wrong logo. Re-run any time
 * to refresh the snapshot.
 */
import { writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { universe } from "./stock-universe";
import { hashStr } from "../src/lib/random";
import { SCREENER_EXCHANGES, fetchScreenerRows, parseStockRow } from "../src/lib/nasdaq";
import { mapPool, resolveTvSymbol } from "./tv-search";

const TOP_N = 500;
const TV_CONCURRENCY = 8;

type Row = {
  ticker: string;
  name: string;
  priceUsd: number;
  mcapUsd: number;
  change24hPct: number;
  vol24hUsd: number;
  image: string | null;
  tvSymbol: string | null;
  hue: number;
  hue2: number;
};

function parseNum(s: string | undefined): number {
  const n = Number((s ?? "").replace(/[$,%\s]/g, ""));
  return Number.isFinite(n) ? n : 0;
}

const screeners = await Promise.all(
  SCREENER_EXCHANGES.map((exchange) => fetchScreenerRows(exchange).catch(() => [])),
);
const rows = screeners
  .flat()
  .map(parseStockRow)
  .filter((r): r is NonNullable<typeof r> => r !== null)
  .sort((a, b) => b.mcapUsd - a.mcapUsd)
  .slice(0, TOP_N);

if (rows.length === 0) {
  console.error("No screener rows fetched — nothing written.");
  process.exit(1);
}

const withTv = await mapPool(rows, TV_CONCURRENCY, async (row) => ({
  ...row,
  tvSymbol: await resolveTvSymbol("stock", row.ticker, row.name),
}));
const resolved = withTv.filter((r) => r.tvSymbol !== null).length;
console.log(`TradingView symbols resolved for ${resolved}/${withTv.length} stocks`);

const domainByTicker = new Map(universe.map((u) => [u.ticker, u.domain] as const));
const finalRows: Row[] = withTv.map((r) => {
  const domain = domainByTicker.get(r.ticker);
  return {
    ...r,
    image: domain ? `https://www.google.com/s2/favicons?domain=${domain}&sz=128` : null,
    hue: hashStr(r.ticker) % 360,
    hue2: (hashStr(r.ticker + (domain ?? r.ticker)) + 40) % 360,
  };
});

const out: string[] = [];
out.push(
  "// AUTO-GENERATED by `bun run gen:stocks` (Nasdaq screener, real market caps) — do not edit by hand.",
);
out.push("// Re-run any time to refresh the snapshot: bun run gen:stocks");
out.push("");
out.push("export type StockSeed = {");
out.push("  ticker: string;");
out.push("  name: string;");
out.push("  priceUsd: number;");
out.push("  mcapUsd: number;");
out.push("  change24hPct: number;");
out.push("  vol24hUsd: number;");
out.push("  image: string | null;");
out.push("  tvSymbol: string | null;");
out.push("  hue: number;");
out.push("  hue2: number;");
out.push("};");
out.push("");
out.push("export const stockSeeds: StockSeed[] = [");
for (const r of finalRows) {
  out.push(
    `  { ticker: ${JSON.stringify(r.ticker)}, name: ${JSON.stringify(r.name)}, ` +
      `priceUsd: ${r.priceUsd}, mcapUsd: ${r.mcapUsd}, change24hPct: ${r.change24hPct}, ` +
      `vol24hUsd: ${r.vol24hUsd}, image: ${JSON.stringify(r.image)}, ` +
      `tvSymbol: ${JSON.stringify(r.tvSymbol)}, hue: ${r.hue}, hue2: ${r.hue2} },`,
  );
}
out.push("];");
out.push("");

const outPath = fileURLToPath(new URL("../src/data/stocks.ts", import.meta.url));
writeFileSync(outPath, out.join("\n"));
console.log(`Fetched ${finalRows.length} stocks (top ${TOP_N} by market cap) → src/data/stocks.ts`);
