/**
 * The stock universe: the S&P 100 mega caps (with GOOGL standing in for both
 * Alphabet share classes → exactly 100 names).
 *
 * - `domain` feeds the logo lookup (Google favicon service).
 * - `sharesB` is shares outstanding in billions, from public filings —
 *   approximate (buybacks/issuance drift a few % per quarter). Market cap is
 *   computed at generation time as real price × sharesB, so mcaps stay
 *   realistic even as prices move.
 * - `altTickers` are tried in order if the primary ticker is unknown to the
 *   quote source (e.g. BNY was BK until its 2025 rebrand).
 */
export type UniverseEntry = {
  ticker: string;
  domain: string;
  sharesB: number;
  altTickers?: string[];
};

export const universe: UniverseEntry[] = [
  { ticker: "AAPL", domain: "apple.com", sharesB: 14.9 },
  { ticker: "ABBV", domain: "abbvie.com", sharesB: 1.77 },
  { ticker: "ABT", domain: "abbott.com", sharesB: 1.74 },
  { ticker: "ACN", domain: "accenture.com", sharesB: 1.57 },
  { ticker: "ADBE", domain: "adobe.com", sharesB: 0.44 },
  { ticker: "AMAT", domain: "appliedmaterials.com", sharesB: 0.81 },
  { ticker: "AMD", domain: "amd.com", sharesB: 1.62 },
  { ticker: "AMGN", domain: "amgen.com", sharesB: 0.54 },
  { ticker: "AMT", domain: "americantower.com", sharesB: 0.467 },
  { ticker: "AMZN", domain: "amazon.com", sharesB: 10.6 },
  { ticker: "AVGO", domain: "broadcom.com", sharesB: 4.68 },
  { ticker: "AXP", domain: "americanexpress.com", sharesB: 0.7 },
  { ticker: "BA", domain: "boeing.com", sharesB: 0.75 },
  { ticker: "BAC", domain: "bankofamerica.com", sharesB: 7.6 },
  { ticker: "BKNG", domain: "booking.com", sharesB: 0.0327 },
  { ticker: "BLK", domain: "blackrock.com", sharesB: 0.148 },
  { ticker: "BMY", domain: "bms.com", sharesB: 2.0 },
  { ticker: "BNY", domain: "bny.com", sharesB: 0.72, altTickers: ["BK"] },
  { ticker: "BRK.B", domain: "berkshirehathaway.com", sharesB: 2.17 },
  { ticker: "C", domain: "citigroup.com", sharesB: 1.87 },
  { ticker: "CAT", domain: "caterpillar.com", sharesB: 0.47 },
  { ticker: "CL", domain: "colgate.com", sharesB: 0.81 },
  { ticker: "CMCSA", domain: "comcast.com", sharesB: 3.7 },
  { ticker: "COF", domain: "capitalone.com", sharesB: 0.383 },
  { ticker: "COP", domain: "conocophillips.com", sharesB: 1.24 },
  { ticker: "COST", domain: "costco.com", sharesB: 0.444 },
  { ticker: "CRM", domain: "salesforce.com", sharesB: 0.956 },
  { ticker: "CSCO", domain: "cisco.com", sharesB: 3.95 },
  { ticker: "CVS", domain: "cvscaremark.com", sharesB: 1.26 },
  { ticker: "CVX", domain: "chevron.com", sharesB: 1.75 },
  { ticker: "DE", domain: "deere.com", sharesB: 0.272 },
  { ticker: "DHR", domain: "danaher.com", sharesB: 0.73 },
  { ticker: "DIS", domain: "thewaltdisneycompany.com", sharesB: 1.81 },
  { ticker: "DUK", domain: "duke-energy.com", sharesB: 0.774 },
  { ticker: "EMR", domain: "emerson.com", sharesB: 0.565 },
  { ticker: "FDX", domain: "fedex.com", sharesB: 0.244 },
  { ticker: "GD", domain: "generaldynamics.com", sharesB: 0.273 },
  { ticker: "GE", domain: "ge.com", sharesB: 1.06 },
  { ticker: "GEV", domain: "gevernova.com", sharesB: 0.274 },
  { ticker: "GILD", domain: "gilead.com", sharesB: 1.24 },
  { ticker: "GM", domain: "gm.com", sharesB: 0.995 },
  { ticker: "GOOGL", domain: "abc.xyz", sharesB: 12.2 },
  { ticker: "GS", domain: "goldmansachs.com", sharesB: 0.31 },
  { ticker: "HD", domain: "homedepot.com", sharesB: 0.992 },
  { ticker: "HON", domain: "honeywell.com", sharesB: 0.65 },
  { ticker: "IBM", domain: "ibm.com", sharesB: 0.92 },
  { ticker: "INTC", domain: "intel.com", sharesB: 4.3 },
  { ticker: "INTU", domain: "intuit.com", sharesB: 0.28 },
  { ticker: "ISRG", domain: "intuitivesurgical.com", sharesB: 0.356 },
  { ticker: "JNJ", domain: "jnj.com", sharesB: 2.4 },
  { ticker: "JPM", domain: "jpmorganchase.com", sharesB: 2.8 },
  { ticker: "KO", domain: "coca-cola.com", sharesB: 4.3 },
  { ticker: "LIN", domain: "linde.com", sharesB: 0.475 },
  { ticker: "LLY", domain: "lilly.com", sharesB: 0.9 },
  { ticker: "LMT", domain: "lockheedmartin.com", sharesB: 0.235 },
  { ticker: "LOW", domain: "lowes.com", sharesB: 0.565 },
  { ticker: "LRCX", domain: "lamresearch.com", sharesB: 1.28 },
  { ticker: "MA", domain: "mastercard.com", sharesB: 0.91 },
  { ticker: "MCD", domain: "mcdonalds.com", sharesB: 0.715 },
  { ticker: "MDLZ", domain: "mondelezinternational.com", sharesB: 1.29 },
  { ticker: "MDT", domain: "medtronic.com", sharesB: 1.28 },
  { ticker: "META", domain: "meta.com", sharesB: 2.53 },
  { ticker: "MMM", domain: "3m.com", sharesB: 0.545 },
  { ticker: "MO", domain: "altria.com", sharesB: 1.69 },
  { ticker: "MRK", domain: "merck.com", sharesB: 2.52 },
  { ticker: "MS", domain: "morganstanley.com", sharesB: 1.58 },
  { ticker: "MSFT", domain: "microsoft.com", sharesB: 7.43 },
  { ticker: "MU", domain: "micron.com", sharesB: 1.11 },
  { ticker: "NEE", domain: "nexteraenergy.com", sharesB: 2.06 },
  { ticker: "NFLX", domain: "netflix.com", sharesB: 0.428 },
  { ticker: "NKE", domain: "nike.com", sharesB: 1.48 },
  { ticker: "NOW", domain: "servicenow.com", sharesB: 0.206 },
  { ticker: "NVDA", domain: "nvidia.com", sharesB: 24.3 },
  { ticker: "ORCL", domain: "oracle.com", sharesB: 2.8 },
  { ticker: "PEP", domain: "pepsico.com", sharesB: 1.37 },
  { ticker: "PFE", domain: "pfizer.com", sharesB: 5.67 },
  { ticker: "PG", domain: "pg.com", sharesB: 2.35 },
  { ticker: "PLTR", domain: "palantir.com", sharesB: 2.4 },
  { ticker: "PM", domain: "pmi.com", sharesB: 1.56 },
  { ticker: "QCOM", domain: "qualcomm.com", sharesB: 1.09 },
  { ticker: "RTX", domain: "rtx.com", sharesB: 1.33 },
  { ticker: "SBUX", domain: "starbucks.com", sharesB: 1.13 },
  { ticker: "SCHW", domain: "schwab.com", sharesB: 1.8 },
  { ticker: "SO", domain: "southerncompany.com", sharesB: 1.1 },
  { ticker: "SPG", domain: "simon.com", sharesB: 0.326 },
  { ticker: "T", domain: "about.att.com", sharesB: 7.18 },
  { ticker: "TMO", domain: "thermofisher.com", sharesB: 0.38 },
  { ticker: "TMUS", domain: "t-mobile.com", sharesB: 1.16 },
  { ticker: "TSLA", domain: "tesla.com", sharesB: 3.23 },
  { ticker: "TXN", domain: "ti.com", sharesB: 0.91 },
  { ticker: "UBER", domain: "uber.com", sharesB: 2.08 },
  { ticker: "UNH", domain: "unitedhealthgroup.com", sharesB: 0.92 },
  { ticker: "UNP", domain: "unionpacific.com", sharesB: 0.604 },
  { ticker: "UPS", domain: "ups.com", sharesB: 0.855 },
  { ticker: "USB", domain: "usbank.com", sharesB: 1.55 },
  { ticker: "V", domain: "visa.com", sharesB: 1.95 },
  { ticker: "VZ", domain: "verizon.com", sharesB: 4.2 },
  { ticker: "WFC", domain: "wellsfargo.com", sharesB: 3.3 },
  { ticker: "WMT", domain: "walmart.com", sharesB: 8.05 },
  { ticker: "XOM", domain: "exxonmobil.com", sharesB: 4.35 },
];
