// AUTO-GENERATED by `bun run gen:coins` from a JSON coin list — do not edit by hand.
// Regenerate after changing the source list: bun run gen:coins

export type CoinSeed = {
  ticker: string;
  name: string;
  priceUsd: number;
  mcapUsd: number;
  change24hPct: number;
  vol24hUsd: number;
  hue: number;
  hue2: number;
};

export const coinSeeds: CoinSeed[] = [
  { ticker: "DOGE", name: "Dogecoin", priceUsd: 0.090051, mcapUsd: 14027093016, change24hPct: -0.3698, vol24hUsd: 914726456, hue: 300, hue2: 341 },
  { ticker: "SHIB", name: "Shiba Inu", priceUsd: 0.00000549, mcapUsd: 3234610319, change24hPct: 0.05665, vol24hUsd: 59084648, hue: 309, hue2: 359 },
  { ticker: "M", name: "MemeCore", priceUsd: 1.13, mcapUsd: 2564131882, change24hPct: -0.07345, vol24hUsd: 1638758, hue: 8, hue2: 50 },
  { ticker: "PUMP", name: "Pump.fun", priceUsd: 0.00389376, mcapUsd: 1538797212, change24hPct: -0.98961, vol24hUsd: 238524805, hue: 43, hue2: 87 },
  { ticker: "PEPE", name: "Pepe", priceUsd: 0.00000361, mcapUsd: 1520014458, change24hPct: -0.32496, vol24hUsd: 185652678, hue: 349, hue2: 58 },
  { ticker: "TRUMP", name: "Official Trump", priceUsd: 2.31, mcapUsd: 604223884, change24hPct: -2.72387, vol24hUsd: 168195054, hue: 87, hue2: 135 },
  { ticker: "PENGU", name: "Pudgy Penguins", priceUsd: 0.00871279, mcapUsd: 547537066, change24hPct: 1.00541, vol24hUsd: 212410523, hue: 112, hue2: 171 },
  { ticker: "币安人生", name: "币安人生 (BinanceLife)", priceUsd: 0.532157, mcapUsd: 532148504, change24hPct: -5.12707, vol24hUsd: 9009232, hue: 216, hue2: 267 },
  { ticker: "SPX", name: "SPX6900", priceUsd: 0.569594, mcapUsd: 530105823, change24hPct: -4.75488, vol24hUsd: 9730608, hue: 290, hue2: 353 },
  { ticker: "BONK", name: "Bonk", priceUsd: 0.00000336, mcapUsd: 295569004, change24hPct: 3.76818, vol24hUsd: 78434387, hue: 129, hue2: 194 },
  { ticker: "APEPE", name: "Ape and Pepe", priceUsd: 0.00000117, mcapUsd: 245814606, change24hPct: 3.15987, vol24hUsd: 9246914, hue: 180, hue2: 242 },
  { ticker: "TIBBIR", name: "Ribbita by Virtuals", priceUsd: 0.244667, mcapUsd: 244653277, change24hPct: 0.38597, vol24hUsd: 2990621, hue: 273, hue2: 320 },
  { ticker: "USELESS", name: "Useless Coin", priceUsd: 0.22049, mcapUsd: 220590608, change24hPct: -18.84775, vol24hUsd: 123704237, hue: 269, hue2: 319 },
  { ticker: "CASHCAT", name: "Cash Cat", priceUsd: 0.219294, mcapUsd: 216367219, change24hPct: -13.03131, vol24hUsd: 37915995, hue: 22, hue2: 72 },
  { ticker: "AI", name: "Artificial Inu", priceUsd: 0.2166, mcapUsd: 214757006, change24hPct: -19.76877, vol24hUsd: 64731160, hue: 167, hue2: 246 },
  { ticker: "WIF", name: "dogwifhat", priceUsd: 0.21459, mcapUsd: 214142760, change24hPct: 0.56165, vol24hUsd: 56191341, hue: 281, hue2: 339 },
  { ticker: "MARSCOIN", name: "MarsCoin", priceUsd: 0.181441, mcapUsd: 181897799, change24hPct: -27.45681, vol24hUsd: 105052229, hue: 125, hue2: 202 },
  { ticker: "FARTCOIN", name: "Fartcoin", priceUsd: 0.177767, mcapUsd: 177783344, change24hPct: 3.04364, vol24hUsd: 37627274, hue: 255, hue2: 334 },
  { ticker: "COCO", name: "coco", priceUsd: 0.171684, mcapUsd: 171685859, change24hPct: -0.30225, vol24hUsd: 45189, hue: 201, hue2: 274 },
  { ticker: "NPC", name: "Non-Playable Coin", priceUsd: 0.02028823, mcapUsd: 163328310, change24hPct: -1.86956, vol24hUsd: 6667365, hue: 72, hue2: 150 },
  { ticker: "B", name: "BUILDon", priceUsd: 0.161562, mcapUsd: 161528615, change24hPct: -9.08412, vol24hUsd: 8317631, hue: 189, hue2: 267 },
  { ticker: "ZCAT", name: "Anonymous Cat", priceUsd: 0.129206, mcapUsd: 125079156, change24hPct: 333.87941, vol24hUsd: 57685420, hue: 351, hue2: 61 },
  { ticker: "DOG", name: "Dog (Bitcoin)", priceUsd: 0.00121287, mcapUsd: 121210528, change24hPct: -1.67208, vol24hUsd: 587539, hue: 49, hue2: 113 },
  { ticker: "MELANIA", name: "Melania Meme", priceUsd: 0.112825, mcapUsd: 112852134, change24hPct: 0.27096, vol24hUsd: 22035208, hue: 40, hue2: 100 },
  { ticker: "CHEEMS", name: "Cheems Token", priceUsd: 5.43708e-7, mcapUsd: 110743154, change24hPct: -2.84953, vol24hUsd: 191846, hue: 344, hue2: 45 },
  { ticker: "ANSEM", name: "The Black Bull", priceUsd: 0.237914, mcapUsd: 98698469, change24hPct: -8.83871, vol24hUsd: 20493386, hue: 57, hue2: 129 },
  { ticker: "SHORT", name: "Bermuda Shorts", priceUsd: 0.00002339, mcapUsd: 97552718, change24hPct: -2.85974, vol24hUsd: 924.79, hue: 293, hue2: 347 },
  { ticker: "AIX", name: "AI XOVIA", priceUsd: 0.947346, mcapUsd: 94734283, change24hPct: 5.26478, vol24hUsd: 864399, hue: 93, hue2: 141 },
  { ticker: "牛来", name: "牛来 (Niu Lai)", priceUsd: 0.09319, mcapUsd: 93021549, change24hPct: -23.11455, vol24hUsd: 26994418, hue: 141, hue2: 201 },
  { ticker: "BABYCLAW", name: "Baby Claw", priceUsd: 0.091376, mcapUsd: 91376294, change24hPct: 0, vol24hUsd: 5.43, hue: 326, hue2: 30 },
  { ticker: "ORDI", name: "ORDI", priceUsd: 4.25, mcapUsd: 89331544, change24hPct: 1.56335, vol24hUsd: 16932300, hue: 259, hue2: 318 },
  { ticker: "AMC", name: "A Meme Coin", priceUsd: 0.087768, mcapUsd: 87767750, change24hPct: 82.13352, vol24hUsd: 135239543, hue: 136, hue2: 213 },
  { ticker: "YZY", name: "YZY", priceUsd: 0.288237, mcapUsd: 86172473, change24hPct: -2.00292, vol24hUsd: 365.99, hue: 257, hue2: 314 },
  { ticker: "BANANAS31", name: "Banana For Scale", priceUsd: 0.00836302, mcapUsd: 83607665, change24hPct: -1.737, vol24hUsd: 4026000, hue: 205, hue2: 254 },
  { ticker: "BULLA", name: "BULLA", priceUsd: 0.074817, mcapUsd: 74949784, change24hPct: -8.90664, vol24hUsd: 4997419, hue: 299, hue2: 358 },
  { ticker: "BABYDOGE", name: "Baby Doge Coin", priceUsd: 4.07228e-10, mcapUsd: 74869652, change24hPct: -1.28483, vol24hUsd: 2699402, hue: 112, hue2: 159 },
  { ticker: "龙虾", name: "龙虾 (Lobster)", priceUsd: 0.073948, mcapUsd: 73933391, change24hPct: -15.00255, vol24hUsd: 8747292, hue: 214, hue2: 268 },
  { ticker: "SHRUB", name: "Lil' Shrub", priceUsd: 0.072704, mcapUsd: 72711570, change24hPct: 48.88843, vol24hUsd: 13446578, hue: 11, hue2: 82 },
  { ticker: "BONER", name: "Boner Coin", priceUsd: 0.072662, mcapUsd: 72662539, change24hPct: 102.73159, vol24hUsd: 45479194, hue: 47, hue2: 115 },
  { ticker: "PURR", name: "Purr", priceUsd: 0.119735, mcapUsd: 71276499, change24hPct: 4.61201, vol24hUsd: 2038074, hue: 74, hue2: 124 },
  { ticker: "BAN", name: "Comedian", priceUsd: 0.0703, mcapUsd: 70290129, change24hPct: 0.27855, vol24hUsd: 5146685, hue: 86, hue2: 131 },
  { ticker: "TURBO", name: "Turbo", priceUsd: 0.00100809, mcapUsd: 69564345, change24hPct: -0.13868, vol24hUsd: 5252512, hue: 155, hue2: 230 },
  { ticker: "BOME", name: "BOOK OF MEME", priceUsd: 0.00090179, mcapUsd: 62224213, change24hPct: 4.61549, vol24hUsd: 80539934, hue: 76, hue2: 131 },
  { ticker: "MHORSE", name: "MEME HORSE", priceUsd: 0.060543, mcapUsd: 60554979, change24hPct: -0.02586, vol24hUsd: 259385, hue: 293, hue2: 345 },
  { ticker: "哈基米", name: "哈基米 (Hajimi)", priceUsd: 0.055704, mcapUsd: 55696212, change24hPct: 223.72486, vol24hUsd: 49112303, hue: 100, hue2: 179 },
  { ticker: "ALD", name: "ALD", priceUsd: 0.054997, mcapUsd: 54997561, change24hPct: -3.0819, vol24hUsd: 501686, hue: 132, hue2: 184 },
  { ticker: "BRETT", name: "Brett", priceUsd: 0.00551828, mcapUsd: 54683769, change24hPct: 3.45796, vol24hUsd: 4726749, hue: 64, hue2: 120 },
  { ticker: "TOSHI", name: "Toshi", priceUsd: 0.00012827, mcapUsd: 53967771, change24hPct: 5.82237, vol24hUsd: 7052810, hue: 210, hue2: 284 },
  { ticker: "APES", name: "APES", priceUsd: 0.059901, mcapUsd: 53910555, change24hPct: 0, vol24hUsd: 3.54, hue: 160, hue2: 200 },
];
